"use client";
import Link from "next/link";
import { ArrowRight, CalendarDays, Clock3, Plus } from "lucide-react";
import { useRelay } from "@/components/relay-provider";
import { Badge, CustomerLink, PageHeading, Panel, ViewLink, Empty } from "@/components/common";
import { Button } from "@/components/ui/button";
import { businessToday, customerName, personName, pendingFollowUps } from "@/lib/domain/selectors";
export default function Dashboard() {
  const {store}=useRelay();
  const today=store.sessions.filter(s=>s.serviceDate.startsWith(businessToday())&&s.status!=="cancelled").sort((a,b)=>a.serviceDate.localeCompare(b.serviceDate));
  const pending=pendingFollowUps(store);
  const due=pending.filter(f=>f.dueAt && f.dueAt<=businessToday());
  const stats=[{name:"客户总数",value:store.customers.length,sub:"每位客户，一份完整档案",href:"/customers"},{name:"今日新增客户",value:store.customers.filter(c=>c.firstVisit===businessToday()).length,sub:"从第一次接待开始记录",href:"/customers?filter=new"},{name:"今日服务人数",value:new Set(today.filter(s=>s.status==="completed"||s.status==="in_progress").map(s=>s.customerId)).size,sub:"已完成与服务中，不含预约",href:"/services"},{name:"待跟进客户",value:new Set(pending.map(f=>f.customerId)).size,sub:`${due.length} 项需今日关注`,href:"/follow-ups"},{name:"高意向客户",value:store.customers.filter(c=>c.tags.includes("高意向")).length,sub:"以客户当前标签为准",href:"/customers?filter=intent"}];
  return <><PageHeading eyebrow={businessToday()} title="工作台" description="接好每一位客户，继续上一次的服务。" action={<Button asChild><Link href="/customers/new"><Plus size={16}/>新建客户</Link></Button>}/>
    <div className="stats-grid">{stats.map((s,i)=><Link href={s.href} className={`stat-card ${i===3?"highlight":""}`} key={s.name}><span>{s.name}<ArrowRight size={15}/></span><strong>{s.value}<small>人</small></strong><p>{s.sub}</p></Link>)}</div>
    <div className="dashboard-grid"><Panel title="今日预约 / 服务" meta={`${today.length} 位客户`} action={<ViewLink href="/services"/>}><div className="schedule-date"><CalendarDays size={16}/><span>{businessToday()}</span><div className="schedule-legend"><i/>服务中 <i/>待到店</div></div><div className="table-scroll"><table className="schedule-table"><thead><tr><th>时间</th><th>客户 / 本次项目</th><th>服务人员</th><th>状态</th><th/></tr></thead><tbody>{today.map(s=><tr key={s.id}><td className="time-cell">{s.serviceDate.slice(11,16)}</td><td><CustomerLink id={s.customerId} name={customerName(store,s.customerId)} sub={s.serviceType}/></td><td>{personName(store,s.staffId)}</td><td><Badge tone={s.status==="in_progress"?"green":s.status==="completed"?"neutral":"amber"}>{s.status==="in_progress"?"服务中":s.status==="completed"?"已完成":"待到店"}</Badge></td><td><ViewLink href={`/customers/${s.customerId}`}>接待档案</ViewLink></td></tr>)}</tbody></table>{!today.length&&<Empty title="今日暂无服务安排"/>}</div><div className="panel-foot"><span className="muted">接待前，先看客户摘要与最近一次反馈</span><Link href="/services/new" className="text-link">新建服务 <Plus size={15}/></Link></div></Panel>
    <Panel title="待跟进事项" meta={`${pending.length}`} action={<ViewLink href="/follow-ups"/>}><div className="followup-list">{pending.slice(0,3).map(f=><Link href={`/customers/${f.customerId}?tab=followups`} key={f.id} className="followup-item"><div className="row-between"><strong>{customerName(store,f.customerId)}</strong><Badge tone={f.dueAt&&f.dueAt<businessToday()?"rose":"amber"}>{f.dueAt&&f.dueAt<businessToday()?"已逾期":f.dueAt===businessToday()?"今日跟进":"计划跟进"}</Badge></div><p>{f.strategy}</p><div className="row-between"><span className="muted">{f.concerns.join(" · ")} · {personName(store,f.staffId)}</span><ArrowRight size={15}/></div></Link>)}</div>{!pending.length&&<Empty title="暂无待跟进事项"/>}</Panel></div>
    <Panel title="最近更新客户" action={<ViewLink href="/customers"/>}><div className="table-scroll"><table><thead><tr><th>客户</th><th>主要诉求</th><th>客户阶段</th><th>最近动态</th><th>更新时间</th><th/></tr></thead><tbody>{[...store.customers].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,4).map(c=>{const h=store.healthProfiles.find(h=>h.customerId===c.id);return <tr key={c.id}><td><CustomerLink id={c.id} name={c.name} sub={c.phone}/></td><td>{h?.goal??"待了解"}</td><td><Badge tone={c.stage==="体验中"?"green":"neutral"}>{c.stage}</Badge></td><td><span className="muted">已更新档案</span></td><td><span className="update-time"><Clock3 size={13}/>{new Date(c.updatedAt).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}</span></td><td><ViewLink href={`/customers/${c.id}`}>查看档案</ViewLink></td></tr>;})}</tbody></table></div></Panel>
  </>;
}
