"use client";
import Link from "next/link";
import { ArrowLeft, ArrowRight, TriangleAlert, ClipboardCheck } from "lucide-react";
import { useRelay } from "./relay-provider";
import { Badge, DetailValue, Empty, NewServiceButton, Panel, ViewLink } from "./common";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "./ui/tabs";
import { CustomerTimeline } from "./customer-timeline";
import { QuestionnaireDetail } from "./questionnaire-detail";
import { PackageCard } from "./package-card";
import { personName, recentSessions, packageBalance, pendingFollowUps } from "@/lib/domain/selectors";
const tabs=[{id:"overview",label:"概览"},{id:"health",label:"健康档案"},{id:"services",label:"服务记录"},{id:"packages",label:"套餐 / 权益"},{id:"followups",label:"跟进记录"}];
export function CustomerDetail({id,initialTab="overview"}:{id:string;initialTab?:string}) {
  const {store}=useRelay();const c=store.customers.find(c=>c.id===id);if(!c)return <Empty title="未找到客户档案" action={<ViewLink href="/customers">返回客户列表</ViewLink>}/>;
  const h=store.healthProfiles.find(h=>h.customerId===id);const last=recentSessions(store,id)[0];const pending=pendingFollowUps(store,id);const next=pending[0];const followups=store.followUps.filter(f=>f.customerId===id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const latestFollowup=followups[0];const packages=store.packages.filter(p=>p.customerId===id);const active=store.sessions.find(s=>s.customerId===id&&s.status==="in_progress");
  return <><div className="detail-top"><Link href="/customers" className="back-link"><ArrowLeft size={14}/>客户档案</Link><span className="muted">/</span><span className="muted">{c.name}</span><span style={{marginLeft:"auto"}}><ViewLink href={`/customers/${id}/edit`}>编辑客户资料 / 问卷</ViewLink></span></div><section className="summary-card"><div className="summary-header"><span className="avatar">{c.name[0]}</span><div><div className="summary-label">客户接待摘要</div><h1>{c.name}</h1><small>{c.gender} · {c.age} · {c.phone}</small></div><div className="tags"><Badge tone="green">{c.stage}</Badge>{c.tags.map(t=><Badge key={t}>{t}</Badge>)}</div><div className="summary-action">{active?<ViewLink href={`/services/${active.id}`}>查看进行中的服务</ViewLink>:<NewServiceButton customerId={id}/>}</div></div><div className="summary-grid"><div className="summary-block"><DetailValue label="主要身体问题">{h?.symptoms}</DetailValue><DetailValue label="核心需求">{h?.goal}</DetailValue></div><div className="summary-block"><DetailValue label="最近一次已完成服务">{last?`${last.serviceDate.slice(5,10)} · ${last.serviceType} · ${personName(store,last.staffId)}`:"尚无已完成服务"}</DetailValue><DetailValue label="最近一次服务反馈">{last?.feedback??"待首次服务后记录"}</DetailValue></div><div className="summary-block"><DetailValue label="当前套餐 / 体验卡">{packages.length?packages.map(p=><div key={p.id}>{p.name} <strong>剩{packageBalance(store,p).remaining}次</strong></div>):"暂无套餐，可直接创建服务"}</DetailValue><DetailValue label="当前成交顾虑">{latestFollowup?.concerns.join("、")||"尚未记录"}</DetailValue></div></div><div className="summary-next"><ClipboardCheck size={17}/><b>下一步</b><span>{next?.strategy??"接待时确认当前需求，服务后补全反馈"}</span><span>{next?`${next.dueAt??"时间待定"} · ${personName(store,next.staffId)}`:"待安排"}</span></div></section>
    <Tabs key={`${id}-${initialTab}`} defaultValue={tabs.some(t=>t.id===initialTab)?initialTab:"overview"}><TabsList aria-label="客户档案分类">{tabs.map(t=><TabsTrigger key={t.id} value={t.id}>{t.label}</TabsTrigger>)}</TabsList>
    <TabsContent value="overview"><div className="detail-columns"><Panel title="客户时间线" meta="把每次服务连起来"><CustomerTimeline customerId={id}/></Panel><div className="section-stack"><Panel title="接待注意事项"><div className="padded"><div className="attention"><TriangleAlert size={16}/><span>{h?.contraindications??"服务前确认健康情况"}</span></div><DetailValue label="服务偏好">{h?.preferences}</DetailValue><DetailValue label="消费观念">{h?.spendingView}</DetailValue></div></Panel><Panel title="当前权益" meta={`${packages.length} 张`}><div className="padded">{packages.length?packages.map(p=><PackageCard key={p.id} pkg={p}/>):<Empty title="暂无套餐 / 体验卡" detail="不购买套餐也可建立服务记录。"/>}</div></Panel>{latestFollowup&&<Panel title="最近一次沟通"><div className="padded"><Badge tone="amber">{latestFollowup.reaction}</Badge><div className="quote">“{latestFollowup.quote}”</div><span className="muted">{latestFollowup.createdAt.slice(5,10)} · {personName(store,latestFollowup.staffId)}记录</span></div></Panel>}</div></div></TabsContent>
    <TabsContent value="health"><div className="section-stack">{h?.questionnaire&&<QuestionnaireDetail q={h.questionnaire}/>}<Panel title="健康档案" meta="客户自述与门店记录"><dl className="health-grid"><DetailValue label="身体症状">{h?.symptoms}</DetailValue><DetailValue label="慢病情况">{h?.chronicConditions}</DetailValue><DetailValue label="血压">{h?.bloodPressure}</DetailValue><DetailValue label="心率">{h?.heartRate?`${h.heartRate} 次/分`:"未记录"}</DetailValue><DetailValue label="主要健康诉求">{h?.goal}</DetailValue><DetailValue label="养生偏好">{h?.preferences}</DetailValue><DetailValue label="健康消费观念">{h?.spendingView}</DetailValue><DetailValue label="禁忌 / 特别关注">{h?.contraindications}</DetailValue><DetailValue label="其他备注">{h?.remarks}</DetailValue></dl></Panel><Panel title="客户基本信息"><dl className="health-grid"><DetailValue label="首次到店">{c.firstVisit}</DetailValue><DetailValue label="客户来源">{c.source}</DetailValue><DetailValue label="接待人员">{personName(store,c.receptionistId)}</DetailValue><DetailValue label="手机号">{c.phone}</DetailValue></dl></Panel></div></TabsContent>
    <TabsContent value="services"><Panel title="历次服务" action={!active&&<NewServiceButton customerId={id}/>}><div className="record-list">{store.sessions.filter(s=>s.customerId===id).sort((a,b)=>b.serviceDate.localeCompare(a.serviceDate)).map(s=><div className="record" key={s.id}><div className="row-between"><h3>{s.serviceDate.slice(0,10)} · {s.serviceType} <Badge tone={s.status==="in_progress"?"green":"neutral"}>{s.status==="completed"?"已完成":s.status==="in_progress"?"服务中":s.status==="cancelled"?"已取消":"待到店"}</Badge></h3><ViewLink href={`/services/${s.id}`}>查看记录</ViewLink></div><p>{personName(store,s.staffId)} · {s.feedback||s.complaint}</p></div>)}</div>{!store.sessions.some(s=>s.customerId===id)&&<Empty title="还没有服务记录" detail="首次到店也可直接开始服务。"/>}</Panel></TabsContent>
    <TabsContent value="packages"><div className="row-between" style={{marginBottom:18}}><h2>客户已购权益</h2><ViewLink href={`/packages/new?customerId=${id}`}>新增套餐 / 权益</ViewLink></div><div className="package-grid">{packages.map(p=><PackageCard key={p.id} pkg={p}/>)}</div>{!packages.length&&<Empty title="暂无套餐权益" detail="可按实际购买情况，手动添加客户的套餐或体验卡。"/>}</TabsContent>
    <TabsContent value="followups"><Panel title="跟进记录" meta="保留客户原话与沟通背景">{followups.map(f=><article key={f.id} className="follow-card"><div className="row-between"><h3>{f.recommendedPackage}<Badge tone="amber">{f.reaction}</Badge></h3><Badge>{f.status==="pending"?"待跟进":"已跟进"}</Badge></div><div className="quote">“{f.quote}”</div><dl className="health-grid" style={{padding:"8px 0"}}><DetailValue label="客户顾虑">{f.concerns.join("、")}</DetailValue><DetailValue label="下一步跟进策略">{f.strategy}</DetailValue><DetailValue label="建议跟进时间 / 负责人">{f.dueAt??"未安排"} · {personName(store,f.staffId)}</DetailValue><DetailValue label="来源服务">{f.sessionId?<ViewLink href={`/services/${f.sessionId}`}>查看本次服务背景</ViewLink>:"独立跟进"}</DetailValue></dl></article>)}{!followups.length&&<Empty title="暂无跟进记录" detail="服务结束后的套餐沟通将记录在这里。"/>}</Panel></TabsContent></Tabs>
  </>;
}
