"use client";
import { useRelay } from "./relay-provider";
import { Badge, DetailValue, Empty, PageHeading, Panel, ViewLink } from "./common";
import { customerName, personName } from "@/lib/domain/selectors";
export function ServiceDetail({id,created}:{id:string;created?:boolean}) {
  const {store,ready}=useRelay();const s=store.sessions.find(s=>s.id===id);if(!s)return <Empty title={ready?"未找到服务记录":"正在读取本机服务记录…"} action={<ViewLink href="/services">返回服务记录</ViewLink>}/>;
  const notes=store.notes.filter(n=>n.sessionId===id).sort((a,b)=>a.at.localeCompare(b.at));const f=store.followUps.find(f=>f.sessionId===id);
  return <>{created&&<div className="success-banner" role="status">服务已建立，并保存到本机演示数据。尚未扣减套餐次数。</div>}<div className="detail-top"><ViewLink href={`/customers/${s.customerId}`}>返回{customerName(store,s.customerId)}的客户档案</ViewLink></div><PageHeading title={`${customerName(store,s.customerId)} · ${s.serviceType}`} description={`${s.serviceDate.slice(0,10)} ${s.serviceDate.slice(11,16)} · ${personName(store,s.staffId)}`} action={<Badge tone={s.status==="in_progress"?"green":"neutral"}>{s.status==="completed"?"已完成":s.status==="in_progress"?"服务中":s.status==="scheduled"?"待到店":"已取消"}</Badge>}/><div className="section-stack"><Panel title="服务前"><dl className="service-detail-grid"><DetailValue label="客户本次主诉">{s.complaint}</DetailValue><DetailValue label="当前身体情况">{s.physicalState}</DetailValue><DetailValue label="需要特别关注">{s.attention}</DetailValue><DetailValue label="关联权益">{store.packages.find(p=>p.id===s.packageId)?.name??"单次服务 · 未使用套餐"}</DetailValue></dl></Panel><Panel title="服务中 · 即时记录" meta={`${notes.length} 条`}><div className="timeline">{notes.map(n=><article className="timeline-item" key={n.id}><span className="timeline-dot"/><div className="timeline-date">{n.at.slice(11,16)}</div><div className="timeline-content"><p><b>客户反馈：</b>{n.feedback}</p><p><b>技师观察：</b>{n.observation}</p><p><b>备注：</b>{n.remark}</p></div></article>)}</div>{!notes.length&&<Empty title="暂无即时记录"/>}{s.status!=="completed"&&<p className="inline-alert">第一版为流程框架；添加即时记录和结束服务将在下一阶段开放。</p>}</Panel><Panel title="服务结束 · 结果与反馈">{s.status==="completed"?<dl className="service-detail-grid"><DetailValue label="服务结果">{s.result}</DetailValue><DetailValue label="客户主观反馈">{s.feedback}</DetailValue><DetailValue label="技师总结">{s.summary}</DetailValue><DetailValue label="身体状况变化">{s.change}</DetailValue><DetailValue label="效果评价（客户自述）">{s.rating}</DetailValue><DetailValue label="套餐扣次">{store.usages.some(u=>u.sessionId===id)?"已记录使用 1 次":"未使用套餐"}</DetailValue></dl>:<Empty title="服务尚未完成" detail="完成后的结果、反馈和身体变化将统一记录在这里。"/>}</Panel><Panel title="本次续单 / 套餐推进">{f?<dl className="service-detail-grid"><DetailValue label="推荐项目 / 套餐">{f.recommendedItem} · {f.recommendedPackage}</DetailValue><DetailValue label="客户反应 / 顾虑">{f.reaction} · {f.concerns.join("、")}</DetailValue><DetailValue label="客户原话">“{f.quote}”</DetailValue><DetailValue label="下一步跟进策略">{f.strategy}</DetailValue><DetailValue label="建议跟进时间">{f.dueAt}</DetailValue></dl>:<Empty title={s.status==="completed"?"本次未进行套餐推进":"待服务结束后记录"} detail="套餐沟通是独立区域，不影响服务记录完整性。"/>}</Panel></div></>;
}
